
platform :ios, '9.0'

target 'MPFavouriteButton_Example' do
    use_frameworks!
    pod 'MPFavouriteButton', :path => '../'

    target 'MPFavouriteButton_Tests' do
        inherit! :search_paths

    
  end
end
